site_name: bspwm
docs_dir: doc
repo_url: https://github.com/baskerville/bspwm
pages:
    - Home: README.md
    - Install: INSTALL.md
    - Manpage: MAN.md
    - Changelog: CHANGELOG.md
    - Contributing: CONTRIBUTING.md
